"""Build a double-blind-safe code supplement from the tracked tree.

The canonical repo carries identity (LICENSE copyright, pyproject authors, and the whole
``.git`` history with the author's name/email on every commit) and internal notes that name
the reviewer dialogue. An anonymized ICML supplement must carry none of that. This script
produces one *without touching the canonical repo*:

  * enumerates only git-tracked files (so gitignored raw data, venvs, run outputs never leak);
  * drops the internal audit/rebuttal notes, committed ``*.pyc`` bytecode, and (by copying
    file-by-file) the entire ``.git`` history;
  * anonymizes the LICENSE copyright line and the pyproject author block in the *copy*;
  * self-checks the result: if any identity token survives anywhere in the export, it aborts.

Run:  python scripts/make_anon_release.py [--out DIR]
Default DIR is a sibling ``dfsl-anon-release/`` next to the repo, cleared and rebuilt each run.
The export is a code supplement; swap the local ICML style shims for the official author-kit
before you actually submit (see RELEASE_NOTES.txt it writes).
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# Tracked files that must NOT ship in the anonymized supplement.
EXCLUDE_EXACT = {
    "paper/audit-findings.md",   # names the reviewer dialogue + every walked-back claim
    "paper/rebuttal-notes.md",   # internal anticipated-objections notes
    # This builder must not ship in the anonymized artifact: its denylist below hardcodes the
    # author's identity tokens, so exporting it would re-introduce exactly what it strips.
    "scripts/make_anon_release.py",
}
EXCLUDE_GLOBS = ("__pycache__/", ".pyc")  # committed bytecode -> junk, never in a release

# Identity tokens that must not appear anywhere in the export tree (case-insensitive).
IDENTITY_TOKENS = ("rafli", "pyhron", "putra pratama", "quantiumintelligence")


def tracked_files() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=PROJECT_ROOT, capture_output=True, text=True, check=True
    ).stdout.splitlines()
    keep = []
    for f in out:
        if f in EXCLUDE_EXACT:
            continue
        if any(g in f for g in EXCLUDE_GLOBS):
            continue
        keep.append(f)
    return keep


def anonymize_license(text: str) -> str:
    return re.sub(r"Copyright \(c\) \d{4} .*", "Copyright (c) 2026 Anonymous", text)


def anonymize_pyproject(text: str) -> str:
    return re.sub(
        r'authors\s*=\s*\[.*?\]',
        'authors = [{ name = "Anonymous", email = "anon@example.com" }]',
        text,
        flags=re.DOTALL,
    )


ANONYMIZERS = {"LICENSE": anonymize_license, "pyproject.toml": anonymize_pyproject}


def scan_for_identity(root: Path) -> list[str]:
    hits = []
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue  # binary (figures, .npy) -- no text identity to leak
        low = text.lower()
        for tok in IDENTITY_TOKENS:
            if tok in low:
                hits.append(f"{p.relative_to(root)}: contains {tok!r}")
    return hits


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=PROJECT_ROOT.parent / "dfsl-anon-release")
    args = ap.parse_args()
    out: Path = args.out.resolve()

    if out == PROJECT_ROOT or PROJECT_ROOT in out.parents:
        print(f"refusing to write the export inside the repo: {out}", file=sys.stderr)
        return 2
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    files = tracked_files()
    anon_applied = []
    for rel in files:
        src = PROJECT_ROOT / rel
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if rel in ANONYMIZERS:
            text = src.read_text(encoding="utf-8")
            new = ANONYMIZERS[rel](text)
            if new == text:
                print(f"WARNING: anonymizer for {rel} changed nothing (pattern drift?)")
            else:
                anon_applied.append(rel)
            dst.write_text(new, encoding="utf-8")
        else:
            shutil.copy2(src, dst)

    (out / "RELEASE_NOTES.txt").write_text(
        "Anonymized ICML code supplement (auto-generated by scripts/make_anon_release.py).\n"
        "- No .git history is included (author identity lived there).\n"
        "- LICENSE / pyproject author fields anonymized.\n"
        "- Internal audit/rebuttal notes excluded.\n"
        "- Style files (icml2026.sty/.bst, algorithm/algorithmic/fancyhdr) are the OFFICIAL\n"
        "  ICML 2026 author-kit files, verified byte-identical (SHA256) -- no swap needed.\n",
        encoding="utf-8",
    )

    hits = scan_for_identity(out)
    print(f"exported {len(files)} files -> {out}")
    print(f"anonymized in copy: {anon_applied or '(none -- check patterns!)'}")
    if hits:
        print("\nIDENTITY LEAK -- export is NOT clean:", file=sys.stderr)
        for h in hits:
            print("  " + h, file=sys.stderr)
        return 1
    print("self-check clean: no identity tokens in the export tree.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
